---
title: "22/05/2023"
author: "ARQUE Maxime"
date: "2023-05-22"
output: html_document
---

<br/>

```{r, include=TRUE, message=FALSE, warning=FALSE}
library(panstripe)
library(ape)
library(patchwork)
library(TreeTools)
library(ggtree)
library(castor)
library(ggplot2)
library(ggpmisc)
set.seed(1234)
```

```{r echo = TRUE, results="hide", message=FALSE, warning=FALSE}
phylo.file.name="/home/maarque/Donnees_projet/Data/SAGs_reduits/SAGs_reduits_reroot.nwk"
rtab.file.name="/home/maarque/Donnees_projet/Data/ALL_SAGS/matrice_binaire_equilibre.tab"
tree <- read.tree(phylo.file.name)
pa <- read_rtab(rtab.file.name)

SAGs=c("496N4_C1","521B10_C1","498P15_C1","529C4_C1","495K23_C1","498B22_C2","498C16_C2","529D18_C3","496A2_C3","529J15_C3","518A17_C3","495L20_C3","528N17_C4","498I20_C5","498A3_C8","527L22_C8","520K10_C9","528J8_C9","P9312")
pa=pa[SAGs,]

```

## <span style="color:blue"> Re-utilisation de panstripe sur l'arbre raciné comme il faut </span>

```{r, include = TRUE}
fit <- panstripe(pa, tree, family="quasipoisson")
```

## <span style="color:blue"> Plots du nouveau fit du jeu de données réduit </span>

```{r, include = TRUE}
plot_pangenome_params(fit)
plot_pangenome_cumulative(fit)
```

## <span style="color:blue"> Arbre de gain et pertes de gènes du nouveau jeu de données </span>

```{r, include = TRUE}
gt <- dplyr::full_join(ggtree::fortify(fit$tree), data.frame(node = fit$tree$edge[,2], trait = fit$data$acc), by = "node")

data_x=gt$x
data_y=gt$y
data_labels=round(gt$trait)

#Ajout d'une colonne complétion pour rajout des % de complétion sur l'arbre

completion=c(100,92.4,92.62,94.63,93.43,91.98,92.45,93.61,96.38,90.76,96.92,93.57,92.07,92.44,97.39,97.74,91.71,90.13,94.57,rep(NA,18))
gt2=cbind(gt,data.frame(completion))

# Plot gainloss
plot_gain_loss(fit,tip_label = FALSE)+geom_tiplab(align=TRUE,size=1.2,color="black")+ geom_text(aes(data_x,data_y),label=data_labels, check_overlap = FALSE, color="red", size=2,hjust=-0.5,vjust=-0.3)+geom_label(label=gt2$completion, size=1.5, x=0.175, color="blue")


```
## <span style="color:blue"> Importation des données de count </span>

```{r, include = TRUE}
data_count=read.table("/home/maarque/Donnees_projet/Data/SAGs_reduits/Data_count/Matrix_data_count2.tab",header = TRUE,sep="\t")

# Comme count nécéssitait de supprimer les "_", je les remets ici pour pouvoir comparer les deux data frames
data_count$Node=sub(" ","_",data_count$Node)

# Ajout d'une colonne total gain/loss au dataframe de count qui n'en a pas
data_count=cbind(data_count,data.frame(data_count$gain+data_count$loss))
colnames(data_count)[6]="total_gainloss"
```

## <span style="color:blue"> Ajout de lettres pour identification des branches non tip </span>

```{r, include = TRUE}
#Attribution des lettres de chaques branches
gt$label[20:37]=c("root","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q")
data_count$Node[20:37]=c("B","G","I","K","J","H","F","M","O","Q","P","N","L","E","D","C","A","root")


#Changement du nom de colonne pour pouvoir merge sur la même colonne
colnames(data_count)[1]="label"
merged_df=merge.data.frame(gt,data_count,by="label")

#Suppression des colonnes inutiles, et changement de nom des colonnes
merged_df = subset(merged_df, select = -c(x,y,branch,angle,parent,node,branch.length,edge.length))
colnames(merged_df)=c("Label","IsTip","gainloss_PANSTRIPE","Number_of_COGS_at_node_COUNT","gain_COUNT","loss_COUNT","gainloss_COUNT")

#Changement de l'ordre des colonnes
merged_df=merged_df[ , c("Label","IsTip","gainloss_PANSTRIPE","gainloss_COUNT","gain_COUNT","loss_COUNT","Number_of_COGS_at_node_COUNT")]

#Arrondi des valeurs
merged_df$gainloss_PANSTRIPE=round(merged_df$gainloss_PANSTRIPE)

#Plot noms des branches
plot_gain_loss(fit,tip_label = FALSE)+geom_tiplab(align=TRUE,size=1.2,color="black")+geom_text(aes(data_x,data_y),label=gt$label, check_overlap = FALSE, color="red", size=2,hjust=-0.5,vjust=-0.3)+geom_label(label=gt2$completion, size=1.5, x=0.175, color="blue")

```

## <span style="color:blue"> Comparaison panstripe/count </span>

```{r, include = TRUE}
#Ajout de deux colonnes de comparaison du total gain/perte
merged_df=cbind(merged_df,round(merged_df$gainloss_PANSTRIPE/merged_df$gainloss_COUNT,2),100-round(merged_df$gainloss_PANSTRIPE*100/merged_df$gainloss_COUNT,2))
#Rename les colonnes
colnames(merged_df)[8:9]=c("panstripe/count","% _diff")

print(merged_df[c(1,3,4,8,9)])

#Calcul de la moyenne de la différence entre panstripe et count
moy_diff=mean(abs(merged_df$`% _diff`), na.rm = T)
print(moy_diff)

#Calcul de la moyenne de la différence entre panstripe et count pour les branches TIP
print(mean(abs(merged_df$`% _diff`[merged_df$IsTip=="TRUE"]),na.rm=T))

#Calcul de la moyenne de la différence entre panstripe et count pour les branches NON TIP
print(mean(abs(merged_df$`% _diff`[merged_df$IsTip=="FALSE"]),na.rm=T))

#Calcul de la moyenne de la différence entre panstripe et count pour les branches TIP SANS P9312 
data=(merged_df$`% _diff`[merged_df$IsTip=="TRUE" & merged_df$Label!="P9312"])
print(mean(abs(data)))

#Soit une perte de % de différence de :
print((mean(abs(merged_df$`% _diff`[merged_df$IsTip=="TRUE"]),na.rm=T))-mean(abs(data)))

```

## <span style="color:blue"> Barplots des résultats </span>

```{r, include = TRUE, warning=FALSE, error=FALSE}
# Barplot du % de différence
ggplot(merged_df, aes(x = Label, y=merged_df$`% _diff`)) + 
    geom_bar(stat = "identity", position = "dodge", fill = "blue")+scale_fill_brewer(palette = "Set1")+theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+ ggtitle("Pourcentage de différence entre panstripe et PGL")+labs(y = "% de différence", x = "Label")

#Barpot de la détection du nombres d'évènements en fonction de panstripe et count.
ggplot(merged_df, aes(x = Label)) +
  geom_bar(aes(y = gainloss_PANSTRIPE, fill = "gainloss_PANSTRIPE"), 
           position = position_dodge(), 
           stat = "identity", 
           alpha = 0.5) +
  geom_bar(aes(y = gainloss_COUNT, fill = "gainloss_PGL"), 
           position = position_dodge(), 
           stat = "identity", 
           alpha = 0.5) +
  labs(title = "Barplot des gainloss_PANSTRIPE et gainloss_PGL",
       x = "Label",
       y = "Nombre d'évènements",
       fill = "") +
  scale_fill_manual(values = c("gainloss_PANSTRIPE" = "blue", "gainloss_PGL" = "red")) +
  theme_minimal()+theme(axis.text.x = element_text(size=6, angle = 45, vjust = 1, hjust=1, color="black"))+theme(axis.text.y = element_text(color="black"))


ggplot(merged_df, aes(x = merged_df$gainloss_PANSTRIPE, y = merged_df$gainloss_COUNT)) + geom_point(color="blue") + geom_smooth(method="lm",se = FALSE, color="red")+geom_text(aes(label=merged_df$Label),vjust=-1, size=2)+
  stat_poly_eq(use_label("eq")) +
  stat_poly_eq(label.y = 0.9) +
  xlab("Nombre d'événements de PANSTRIPE") + 
  ylab("Nombre d'événements de PGL") + 
  ggtitle("Nombre d'événements de PANSTRIPE vs PGL") 


```

## <span style="color:blue"> Recherche des COGs avec un seul SAGs </span>
```{r, include = TRUE, warning=FALSE, error=FALSE}
pa2=rbind(pa,colSums(pa))
rownames(pa2)[20]="somme_COGs"

#COGs avec 0, moins de 2 ou plus de 2 SAGs
matrix_SAGs_sup2=pa2[,pa2["somme_COGs",] >=2]

matrix_SAGs_sup2_2=matrix_SAGs_sup2[1:19,]

matrix_SAGs_inf1=pa2[,pa2["somme_COGs",] <2]
matrix_SAGs_0=pa2[,pa2["somme_COGs",] == 0]

#SAGs avec un seul COG
pa3=cbind(pa,rowSums(pa))
print(pa3[,7825]) # y'en a pas

write.table(t(matrix_SAGs_sup2_2), file="/home/maarque/Donnees_projet/Data/SAGs_reduits/matrix_SAGs_reduits.tab", row.names=TRUE, col.names=TRUE, sep="\t", quote=FALSE)

# Nombre de COGs avec un seul SAGs
matrix_SAGs_inf1=matrix_SAGs_inf1[1:19,]


```



<br/>
<br/>
