---
title: "19_06_2023"
author: "ARQUE Maxime"
date: "2023-06-19"
output: html_document
---

# <span style="color:red"> Etude refaite pour être plus précis (Genomes_refs_AA_2) </span>

## <span style="color:blue"> Script de toute l'analyse </span>

```{r, engine='bash', eval=FALSE}
#Création DB
mmseqs createdb all-pop.fa target_db
# --search-type 3 pour NT et 2 pour PROT
mmseqs createindex target_db tmp --search-type 2

#Blast
files=$(find -name "protein.faa*")
for file in $files ; do name=$(echo "$file" | awk -F'/' '{print $3}') ; mmseqs easy-search "$file" target_db "result_${name}" tmp --format-output "query,target,evalue,qcov,tcov,pident,qlen,tlen,alnlen" ; done

# Tri des données 
for file in result_GCF_*.1; do output_file="CDS_COGS/COGS_$(basename "$file" | cut -d'.' -f1).txt"; awk '{OFS="\t"} { if ($3<1e-5 && $6>0.3) { ratio = ($7 <= $8) ? $9/$7 : $9/$8; if (ratio > 0.75) { print $1,$2,$3,$6,ratio }}}' "$file" | cut -d "|" -f1 | sort | uniq -c | sort -k2 | awk '{if (!max[$2] || $1 > max[$2]) {max[$2] = $1; name[$2] = $3}} END {for (id in name) print id, name[id]}' > "$output_file"; done

# Fichier overview
for file in COGS_result_*; do count=$(wc -l < "$file"); base=$(basename "$file" .txt); echo -e "$count\t$file\tGCF_$(echo "$base" | awk -F '_' '{print $4}')"; done | sort -k1 -n -r > Overview
join -1 3 -2 1 -t $'\t' <(sort -k3 Overview) <(sort -k1 Correspondance_RefSeq_Strain) | sort -k2 -n -r | awk '{OFS="\t"} {print $2,$4,$1,$3}'> Data_overview

#Récupérer les séquences nt des COGS
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359575.txt ./data/GCF_027359575.1/cds_from_genomic.fna > COGS_NT/GCF_027359575
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000015685.txt ./data/GCF_000015685.1/cds_from_genomic.fna > COGS_NT/GCF_000015685
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359355.txt ./data/GCF_027359355.1/cds_from_genomic.fna > COGS_NT/GCF_027359355
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000015965.txt ./data/GCF_000015965.1/cds_from_genomic.fna > COGS_NT/GCF_000015965
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000012465.txt ./data/GCF_000012465.1/cds_from_genomic.fna > COGS_NT/GCF_000012465
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000018065.txt ./data/GCF_000018065.1/cds_from_genomic.fna > COGS_NT/GCF_000018065
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359525.txt ./data/GCF_027359525.1/cds_from_genomic.fna > COGS_NT/GCF_027359525
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359415.txt ./data/GCF_027359415.1/cds_from_genomic.fna > COGS_NT/GCF_027359415
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000015665.txt ./data/GCF_000015665.1/cds_from_genomic.fna > COGS_NT/GCF_000015665
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000015705.txt ./data/GCF_000015705.1/cds_from_genomic.fna > COGS_NT/GCF_000015705
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359475.txt ./data/GCF_027359475.1/cds_from_genomic.fna > COGS_NT/GCF_027359475
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000015645.txt ./data/GCF_000015645.1/cds_from_genomic.fna > COGS_NT/GCF_000015645
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000007925.txt ./data/GCF_000007925.1/cds_from_genomic.fna > COGS_NT/GCF_000007925
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000012645.txt ./data/GCF_000012645.1/cds_from_genomic.fna > COGS_NT/GCF_000012645
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359375.txt ./data/GCF_027359375.1/cds_from_genomic.fna > COGS_NT/GCF_027359375
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359395.txt ./data/GCF_027359395.1/cds_from_genomic.fna > COGS_NT/GCF_027359395
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000011485.txt ./data/GCF_000011485.1/cds_from_genomic.fna > COGS_NT/GCF_000011485
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_027359595.txt ./data/GCF_027359595.1/cds_from_genomic.fna > COGS_NT/GCF_027359595
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000018585.txt ./data/GCF_000018585.1/cds_from_genomic.fna > COGS_NT/GCF_000018585
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000011465.txt ./data/GCF_000011465.1/cds_from_genomic.fna > COGS_NT/GCF_000011465
python3 ScriptAA.py ./CDS_COGS/COGS_result_GCF_000158595.txt ./data/GCF_000158595.1/cds_from_genomic.fna > COGS_NT/GCF_000158595

#Création d'un fichier par COG qui contient toutes les séquences
names=$(find -name "GCF_*") ; cat $names > All_GCF
python3 script.py

# Regrouper toutes les séquences en un seul fichier au bon format
for dir in */ ; do cd $dir ; cat *.txt | grep -v '^$' | sed -r 's/[0-9]+ //' | fold -w 80 -s > "All_COGS$(basename "$(pwd)").txt ; cd .. ; done

#Création des profils HMM
files=$(find /databis/gardon/PROCHLOROCOCCUS/phylogeny-core-genes/ -name "og*.fna.aligned.fasta*")
for file in $files ; do number=$(echo "$file" | cut -d'/' -f6) ; if [ ! -d "$number" ]; then : ; fi ; output="$number/HMM_COG_$number" ; hmmbuild "$output" "$file"; [ ! -s "$output" ] && rm "$output"; done

#Récupération des fichiers d’hélène pour Mapali
files=$(find /databis/gardon/PROCHLOROCOCCUS/phylogeny-core-genes/ -name "og*.fna.aligned.fasta")
for file in $files ; do number=$(echo "$file" | cut -d'/' -f6) ; cp $file ./$number ; done

#Utilisation du HMM pour aligner les séquences
files=$(find -name "HMM_*")
for file in $files ; do name=$(echo $file | cut -d "/" -f2) ; cd $name ; if ls All_COGS* 1> /dev/null 2>&1; then hmmalign --outformat phylip --dna --trim --mapali og* HMM_COG* All_COGS* > phylip$name ; seqret phylip$name Alignement_$name.fasta ; awk -i inplace '!/MIT9312/' RS=">" ORS=">" Alignement_$name.fasta ; awk -i inplace '!/^>$/ || NR==1' Alignement_$name.fasta ; fi ; cd .. ; done

# Concaténation de tous les COGS (nouveaux identifiées + ceux déjà identifiés) 
files=$(find -name "Align*" -type f | sort -t '/' -k2n)
amas concat -i $files -f fasta -d dna --concat-out ALL_concatenated_cogs.fna
sed -i 's/?/-/g' ALL_concatenated_cogs.fna
```

## <span style="color:blue"> Comparaison des protéines manquantes </span>

```{r, engine='bash', eval=FALSE}
COGS=$(more all_COGS | cut -d " " -f1)
PROTS=$(more all_prots | grep ">" | cut -d " " -f1 | cut -d ">" -f2)

#Utilisation d'un script python pour identifier les protéines qui diffèrent (7815)
#Il semble que soit les protéines ne blastent pas, soit elles blastent mais ont des data en desous des seuils prédéfinis

```
